[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["views/**", "assets/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
